services:
  videosdk-auth:
    build: .
    container_name: videosdk-auth
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - videosdk-net

networks:
  videosdk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
